package eular;

/*
* Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*
* */

public class Solution45 {
    public static void main(String args[]) {
        Solution45 solution = new Solution45();
        solution.solve();
    }

    private void solve() {
        int i = 5;
        long max = 40755;
        while (true) {
            i++;
            long k = i * (2 * i - 1);
            if (k > max && isPentogonal(k)) {
                max = k;
                break;
            }
        }

        System.out.println(max);
    }

    private boolean isPentogonal(long n) {
        Double t = (1 + Math.sqrt(24 * n + 1)) / 6;
        return (t == Math.floor(t)) && !Double.isInfinite(t);

    }
}
